server:
    port: 8080
spring:
    datasource:
        name: demo
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root

        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        host: 127.0.0.1
        port: 6379
        database: 0
        password:
        timeout: 5000
        prefix: phoenix-demo
        jedis:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 0

mybatis-plus:
    global-config:
        banner: false
    mapper-locations: classpath:com/bruce/demo/web/sqlmap/auto/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

log:
    packageName: com.bruce.demo.web
    projectName: phoenix-demo

swagger:
    enable: true

auth:
    enable: false
    excludeUrls: [ "/demo/**","/ws/demo" ]
    defaultExcludeUrls: [ "/auth/login", "/auth/secretKey", "/auth/showResScript", "/auth/refresh", "/auth/images/captcha", "/auth/redirect", "/error" ]
    swaggerUrls: [ "/doc.html", "/v2/api-docs", "/v2/api-docs-ext","/swagger-resources", "/webjars/**" ]
    token:
        type: REDIS
        expire: 172800000
        name: authtoken
    captcha:
        enable: true
        lineCount: 100
        expire: 120
        length: 16
        name: rid
        codeCount: 4
    retry:
        expire: 7200
        nums: 5

