nacos:
    config:
        server-addr: 127.0.0.1:8848
        data-ids: phoenix-demo.yml,common.yml,env-data.yml
        namespace: phoenix
        auto-refresh: true
        type: yaml
        group: DEFAULT_GROUP
        bootstrap:
            enable: true
            log-enable: true
